version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5000"  
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT} 
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME} 
      - API_ID=${API_ID}  
      - API_HASH=${API_HASH}  
    volumes:
      - .:/app  
    depends_on:
      - db  

  db:
    image: postgres:13 
    environment:
      POSTGRES_USER=${DATABASE_USER} 
      POSTGRES_PASSWORD=${DATABASE_PASSWORD} 
      POSTGRES_DB=${DATABASE_NAME} 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "${DATABASE_PORT}:5432" 

volumes:
  postgres_data:
    driver: local
